package secretwriting.UnitTests;

public class AccuracyMeasure {
	public static void main(String[] args) {
		String original = "France's health minister announced on Saturday the first death from coronavirus in Europe. The patient was an 80-year-old Chinese tourist who went to France in mid-January and was hospitalized later that month, according to French Health Minister Agnès Buzyn. The head of the U.S. Centers for Disease Control and Prevention said the new coronavirus, which has killed more than 1,500 people and is still spreading in China, could be around for at least another year. The outbreak has infected ten of thousands of people worldwide. There are 15 confirmed cases in the U.S., but none are said to be suffering serious symptoms. The agency is setting up five labs around the U.S. where people with flu-like symptoms can be tested for coronavirus if their flu results are negative. The virus, dubbed COVID-19, has spread to more than two dozen countries.".toLowerCase();
		String decipherment = "Iall Ceans Fack to school Ior kids, Vhich Ceans Core cars and Fuses on the roads. drivers also need to Vatch out Ior increased pedestrian traIIic in the CorninN and aIternoon as children Valk to and IroC school and their neiNhForhood Fus stops. the Iirst rain in a IeV Veeks can Fe particularlD danNerous, as Vater pools on top oI dust and oil that haven't had a chance to Vash aVaD and Cakes the paveCent extreCelD slipperD. Iall IoliaNe is certainlD FeautiIul, Fut as leaves FeNin to Iall, theD litter the roads, CakinN streets slick Vhile oFscurinN traIIic lines and other paveCent CarkinNs. theD also hide potholes and other road hamards. and Vhen it rains, it can Cake those Vet leaves on the roadVaD as danNerous as ice. and Vhere there are turninN leaves, there are leaI peepers. these leaI-peepinN drivers tend to craVl alonN the roads and Cake unpredictaFle stops to adCire the chanNinN IoliaNe. iI Dou're drivinN Fehind a car Vith out-oI-state plates, Nive theC a little extra space gust in case theD stop short Ior a photo. cold Iall CorninNs oIten lead to IoN, Vhich can NreatlD liCit Dour drivinN visiFilitD and perception oI distance. IoN tends to occur in loV places or areas surrounded FD hills, Vater, Countains, and trees. one coCCon Cistake drivers Cake durinN IoNND conditions is puttinN on their hiNh FeaCs instead oI staDinN Vith their loV FeaCs. this onlD Cakes visiFilitD Vorse Fecause Dour hiNh FeaCs Vill Founce oII the IoN and create Nlare. Vhen drivinN throuNh IoN, sloV doVn and staD Vell Fehind the car in Iront oI Dou so Dou'll have adequate tiCe to stop iI Dou need to. durinN the Iall, teCperatures tend to drop draCaticallD durinN the niNht, Vhich can lead to CorninN Irost and icD spots on the road. this is especiallD coCCon on FridNes, overpasses, and shaded areas oI the road. Iall is also a Fad tiCe Ior sun Nlare on the roads. sun Nlare can iCpact Dour siNht Ior seconds aIter exposure, CakinN it hard to see pedestrians, oncoCinN traIIic, or the car in Iront oI Dou. accordinN to the national hiNhVaD traIIic saIetD adCinistration, drivers descriFe FeinN \"Flinded\" aIter exposure, and this soCetiCes leads to accidents or near Cisses. sun Nlare can also cause proFleCs Vhen the sun sets Fehind drivers. in this case, sunliNht can Founce oII Dour rearvieV Cirror or reIlect oII traIIic liNhts up ahead, and this can Flind Dou Ior a split second Vhile Dour eDes adgust. it can also Cake it hard (or iCpossiFle) to see traIIic liNhts, Vhich can prevent Dou IroC knoVinN iI Dou're supposed to stop or No. the Iall season FrinNs an increase in deer activitD Fecause it's their tiCe Ior CatinN and CiNratinN. iI Dou live in a deer-heavD area, Vatch Ior dartinN deer, especiallD Vhen drivinN at niNht.";
		int counter = 0;
		for (int i = 0; i < original.length(); i++) {
			if (original.charAt(i) != decipherment.charAt(i)) {
				counter++;
			}
		}
		System.out.println(((float)(original.length() - counter) / original.length()) * 100 + "%");
	}
}
